In [1]:
import warnings
warnings.simplefilter('ignore')

Import pandas libraries and  numpy

In [2]:
import numpy as np
import pandas as pd

 Data visualization library
 
 seaborn lib use for statisctical visualization

In [3]:
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [4]:
import sklearn

Import dataset

In [5]:
dataset =pd.read_excel('C:/Users/abishek/Documents/Abishek_DATA SCIENCE/Dataset/student_dataset.xlsx')

In [ ]:
dataset.head()

## dataset shape

In [7]:
dataset.shape

(367, 6)

In [ ]:
dataset.info()

In [ ]:
dataset.isnull().sum()

In [10]:
dataset.describe()

S.NO        ATTN      THEORY  Daily assn       TOTAL
count  367.000000  367.000000  367.000000  367.000000  367.000000
mean   184.000000   18.926431   12.495913   13.405995   41.231608
std    106.088014    3.607450   12.815605    9.770943   21.568883
min      1.000000    1.000000    0.000000    0.000000    0.000000
25%     92.500000   15.000000    0.000000    0.000000   25.000000
50%    184.000000   20.000000   12.000000   15.000000   40.000000
75%    275.500000   20.000000   24.000000   25.000000   57.500000
max    367.000000   25.000000   42.000000   25.000000   87.000000

In [11]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   S.NO         367 non-null    int64 
 1   ATTN         367 non-null    int64 
 2   THEORY       367 non-null    int64 
 3   Daily assn   367 non-null    int64 
 4   TOTAL        367 non-null    int64 
 5   certificate  367 non-null    object
dtypes: int64(5), object(1)
memory usage: 17.3+ KB


In [12]:
data=dataset.drop(['S.NO','TOTAL'],axis=1)

In [13]:
data

ATTN  THEORY  Daily assn    certificate
0      20      38          25    DISTINCTION
1      15      25           0     COMPLETION
2      20      31          25    FIRST CLASS
3      20      25          25    FIRST CLASS
4      20      17          15    FIRST CLASS
..    ...     ...         ...            ...
362    15       0          10  PARTICIPATION
363    20       9          25     COMPLETION
364    15      20          25    FIRST CLASS
365    15       0          10  PARTICIPATION
366    20      23          10     COMPLETION

[367 rows x 4 columns]

## get unique value in certificate

In [14]:
data['certificate'].unique()

array(['DISTINCTION', 'COMPLETION', 'FIRST CLASS', 'PARTICIPATION'],
      dtype=object)

### groupby function used to group the typpe of certificate and size is total number is printed

In [15]:
data.groupby('certificate').size()

certificate
COMPLETION       117
DISTINCTION       32
FIRST CLASS       66
PARTICIPATION    152
dtype: int64

### Encoding the data

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
data.iloc[:,3] = LabelEncoder().fit_transform(data.iloc[:,3])

In [18]:
data

ATTN  THEORY  Daily assn certificate
0      20      38          25           1
1      15      25           0           0
2      20      31          25           2
3      20      25          25           2
4      20      17          15           2
..    ...     ...         ...         ...
362    15       0          10           3
363    20       9          25           0
364    15      20          25           2
365    15       0          10           3
366    20      23          10           0

[367 rows x 4 columns]

In [46]:
x = data.iloc[:,:-1]

In [47]:
x

ATTN  THEORY  Daily assn
0      20      38          25
1      15      25           0
2      20      31          25
3      20      25          25
4      20      17          15
..    ...     ...         ...
362    15       0          10
363    20       9          25
364    15      20          25
365    15       0          10
366    20      23          10

[367 rows x 3 columns]

In [21]:
type(x)

numpy.ndarray

In [22]:
y= data.iloc[:,3].values

In [23]:
y

array([1, 0, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2, 2, 2, 0, 3, 0, 0, 2, 0, 2, 1,
       2, 3, 1, 0, 3, 1, 2, 1, 0, 0, 0, 3, 2, 0, 0, 0, 1, 2, 1, 0, 1, 1,
       2, 0, 0, 0, 3, 0, 1, 2, 2, 2, 0, 3, 0, 2, 0, 1, 2, 2, 2, 1, 0, 3,
       1, 0, 3, 3, 0, 3, 1, 3, 0, 0, 3, 3, 3, 3, 1, 0, 2, 0, 3, 3, 0, 3,
       3, 2, 3, 3, 3, 2, 2, 0, 2, 0, 0, 1, 0, 1, 1, 2, 1, 2, 3, 1, 0, 3,
       3, 1, 3, 0, 3, 0, 0, 3, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1,
       3, 0, 0, 3, 3, 3, 3, 3, 3, 0, 3, 3, 3, 3, 3, 3, 1, 0, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       0, 0, 0, 3, 3, 3, 3, 3, 3, 0, 3, 0, 1, 1, 0, 2, 0, 2, 0, 2, 0, 0,
       2, 0, 0, 3, 0, 0, 2, 0, 2, 2, 0, 3, 1, 3, 0, 2, 0, 1, 0, 0, 0, 2,
       2, 2, 0, 2, 2, 2, 0, 2, 2, 3, 0, 1, 3, 2, 3, 3, 1, 2, 1, 0, 3, 2,
       2, 2, 2, 3, 0, 0, 3, 3, 3, 0, 0, 0, 3, 3, 0, 3, 2, 0, 3, 3, 0, 3,
       3, 3, 0, 3, 0, 3, 3, 3, 0, 0, 0, 0, 3, 3, 3, 0, 0, 3, 3, 0, 0, 3,
       0, 0, 3, 0, 0, 3, 3, 2, 3, 3, 3, 0, 0, 3, 0,

## convert DataFrame

In [24]:
x_frame = pd.DataFrame(x,columns=['ATTN','Theory','Daily Assn'])

In [25]:
x_frame

ATTN  Theory  Daily Assn
0      20      38          25
1      15      25           0
2      20      31          25
3      20      25          25
4      20      17          15
..    ...     ...         ...
362    15       0          10
363    20       9          25
364    15      20          25
365    15       0          10
366    20      23          10

[367 rows x 3 columns]

In [26]:
lab = sklearn.preprocessing.LabelEncoder()

In [27]:
y_transfrom=lab.fit_transform(y)

In [28]:
y_frame = pd.DataFrame(y_transfrom)

In [29]:
y_frame

0
0    1
1    0
2    2
3    2
4    2
..  ..
362  3
363  0
364  2
365  3
366  0

[367 rows x 1 columns]

# Imp lib For Training set & Testing Set

In [30]:
from sklearn.model_selection import train_test_split

### Split Dataset with Appropriate variables

##### test_size =0.3 means 30% dataset random picked and allocate to test set abd remaining is allocated to training set
**Training** =75%
Testing=25%
##### random_state control shuffling dataset bcz numbers are picked to allocate training set and traningset inorder to remove human bias

In [31]:
x_train, x_test, y_train, y_test = train_test_split(x_frame ,y_frame ,test_size =0.2 ,random_state=0)

In [32]:
x_train

ATTN  Theory  Daily Assn
63     25      36          25
241    25      21          25
306    15       0           0
317    20      21          10
245    15       0           0
..    ...     ...         ...
323    20       7          25
192    20       0          25
117    20      16           0
47     20      22          15
172    15       0           0

[293 rows x 3 columns]

In [33]:
x_test

ATTN  Theory  Daily Assn
106    15       0          15
259    20      27          15
45     20       0          20
26     15       0           0
78     15       0           0
..    ...     ...         ...
159    15       0           0
74     20      16          15
170    20       0           0
114    15       0           0
295    20      19          15

[74 rows x 3 columns]

In [34]:
y_test

0
106  3
259  0
45   0
26   3
78   3
..  ..
159  3
74   0
170  3
114  3
295  3

[74 rows x 1 columns]

In [35]:
y_train

0
63   1
241  2
306  3
317  0
245  3
..  ..
323  0
192  0
117  3
47   0
172  3

[293 rows x 1 columns]

# K-Nearest Neighbour
**max_k_value=19**

## imp knn lib

In [36]:
from sklearn.neighbors import KNeighborsClassifier

In [37]:
knn=KNeighborsClassifier(n_neighbors=5)

## **Fitting values in KNN**

In [38]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [39]:
y_predict = knn.predict(x_test)

In [40]:
y_predict

array([3, 2, 0, 3, 3, 3, 3, 3, 0, 0, 3, 0, 0, 2, 0, 1, 0, 2, 1, 3, 3, 0,
       1, 0, 3, 3, 3, 0, 0, 2, 3, 2, 3, 3, 0, 0, 2, 3, 3, 0, 0, 3, 0, 3,
       0, 0, 0, 0, 3, 3, 3, 2, 0, 1, 3, 0, 0, 3, 2, 0, 2, 0, 1, 0, 3, 0,
       0, 3, 0, 3, 0, 3, 3, 0])

## **Model Evaluation & Performance Metrics**

In [41]:
knn.score(x_train,y_train)

0.7849829351535836

In [42]:
knn.score(x_test,y_test)

0.6891891891891891

### Importing Necessary Metric

In [43]:
from sklearn.metrics import confusion_matrix

In [44]:
con_matrix = confusion_matrix(y_test,y_predict)

In [45]:
con_matrix

array([[15,  0,  2,  1],
       [ 0,  3,  2,  0],
       [ 7,  2,  5,  0],
       [ 9,  0,  0, 28]])