# NUMPY

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [2]:
np.version.version

'2.0.2'

# ONE DIMENTIONAL ARRAY

## SYNTAX : numpy.array([values]) 

In [3]:
first_array = np.array([[1, 2, 3, 4, 5]])

In [4]:
first_array

array([[1, 2, 3, 4, 5]])

In [5]:
type(first_array)

numpy.ndarray

# TWO DIMENTIONAL ARRAY

In [6]:
second_array = np.array([(7,8,9),(10,11,12)])
second_array

array([[ 7,  8,  9],
       [10, 11, 12]])

# THREE DIMENTIONAL ARRAY

In [7]:
third_array = np.array([[(7,8,9),(10,11,12)],[(13,14,15),(16,17,18)],[(19,20,21),(22,23,24)]])
third_array

array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [8]:
zero_array = np.zeros((2,2))
zero_array

array([[0., 0.],
       [0., 0.]])

In [9]:
one_array = np.ones((2,2))
one_array

array([[1., 1.],
       [1., 1.]])

# LINESPACE

In [10]:
SPACED_NUM= np.linspace(0,20,10)
print(SPACED_NUM)

[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]


# ARRAY MANIPULATION

In [11]:
my_array = np.array([(1,2,3),(4,5,6)])
ar_ones = np.ones((3,3))

# TRANSPOSE

In [12]:
matr_tranpose = np.transpose(my_array)

In [13]:
print(matr_tranpose)

[[1 4]
 [2 5]
 [3 6]]


# FLATENING ARRAY

In [14]:
matr_tranpose.ravel()

array([1, 4, 2, 5, 3, 6])

In [15]:
import pandas as pd #for data manipulation and analysis

In [16]:
pd.__version__

'2.2.2'

In [17]:
a1 = pd.Series(['Rakshana','Guptha','Santhiya','Guhan','Rasik'],index = [0,1,2,3,4]) #for converting into certain format

In [18]:
a1

0    Rakshana
1      Guptha
2    Santhiya
3       Guhan
4       Rasik
dtype: object

In [19]:
season = {"winter":{1:'nov',2:'dec',3:'jan',4:'feb'},"dry":{1:'mar',2:'apr',3:'may',4:'jun'},"rain":{1:'july',2:'aug',3:'sep',4:'oct'}}

In [20]:
d = pd.DataFrame(season,columns=["winter","dry","rain"])

In [21]:
d

winter  dry  rain
1    nov  mar  july
2    dec  apr   aug
3    jan  may   sep
4    feb  jun   oct

In [22]:
foods_and_drinks = {"drinks":{1:'lemon juice',2:'orange juice',3:'watermelon juice',4:'fruit mixer',5:'lassi'},"food_veg":{1:'sambar',2:'lemon',3:'curd',4:'rasam',5:'keera saaru'},"food_nonveg":{1:'chicken',2:'mutton',3:'beef',4:'pork',5:'lamp'}}

In [23]:
h = pd.DataFrame(foods_and_drinks)

In [24]:
h

drinks     food_veg food_nonveg
1       lemon juice       sambar     chicken
2      orange juice        lemon      mutton
3  watermelon juice         curd        beef
4       fruit mixer        rasam        pork
5             lassi  keera saaru        lamp

In [25]:
A = pd.DataFrame(np.random.randint(0,500,size=(20,3)),columns=('apple','orange','grape')) # or columns=list('abcdef') and random.randint is in the numpy library for generate the random numbers

In [26]:
A.head(5)

apple  orange  grape
0    471     212    499
1     35     140    390
2    393     186    441
3    341     107    195
4    492      87    288

In [29]:
A.to_csv('C:/Users/abishek/Desktop/pandas.csv')

In [30]:
D = pd.read_csv('C:/Users/abishek/Desktop/pandas.csv')

In [31]:
D

Unnamed: 0  apple  orange  grape
0            0    471     212    499
1            1     35     140    390
2            2    393     186    441
3            3    341     107    195
4            4    492      87    288
5            5    273     390    488
6            6    453     100    446
7            7    450      53    159
8            8    154     392    163
9            9    383     381    148
10          10    123     277     90
11          11    219     451    271
12          12    137     106    138
13          13    474     238    365
14          14     57     334    293
15          15    116     239    141
16          16    146     358      3
17          17    262     344    162
18          18    225     178    334
19          19     76     218    271

In [32]:
D.shape #for identify the rows and columns

(20, 4)

In [33]:
D.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  20 non-null     int64
 1   apple       20 non-null     int64
 2   orange      20 non-null     int64
 3   grape       20 non-null     int64
dtypes: int64(4)
memory usage: 772.0 bytes


In [36]:
J = pd.read_csv('C:/Users/abishek/Documents/Abishek_DATA SCIENCE/Dataset/retail_dataset.csv')

In [37]:
J

0       1       2       3       4       5       6
0     Bread    Wine    Eggs    Meat  Cheese  Pencil  Diaper
1     Bread  Cheese    Meat  Diaper    Wine    Milk  Pencil
2    Cheese    Meat    Eggs    Milk    Wine     NaN     NaN
3    Cheese    Meat    Eggs    Milk    Wine     NaN     NaN
4      Meat  Pencil    Wine     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...     ...     ...
310   Bread    Eggs  Cheese     NaN     NaN     NaN     NaN
311    Meat    Milk  Pencil     NaN     NaN     NaN     NaN
312   Bread  Cheese    Eggs    Meat  Pencil  Diaper    Wine
313    Meat  Cheese     NaN     NaN     NaN     NaN     NaN
314    Eggs    Wine   Bagel   Bread    Meat     NaN     NaN

[315 rows x 7 columns]

In [38]:
J.shape

(315, 7)

In [39]:
J.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 315 entries, 0 to 314
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       315 non-null    object
 1   1       285 non-null    object
 2   2       245 non-null    object
 3   3       187 non-null    object
 4   4       133 non-null    object
 5   5       71 non-null     object
 6   6       41 non-null     object
dtypes: object(7)
memory usage: 17.4+ KB


#### 