# Numberical Py                       
#### diff b/w array and tuples,dict,list("array is single valuable and share same data types)
                                    
##### Mathematical lib in Py
##### Travis Oliphant in 2005
##### these can perform:
            matematical and logical operation on array
            fourier transform and routine for shape manipulation
            collection of high level mathamatical function
##### what is array?
##### array is single valuable and share same data types            
##### indexed by +ve integers
##### index is start from zero to max in py
##### ex: array  ={1,12,54,5412}
          tuples ={1,12,54,5412}

#  Pandas

#### pandas library used for data set
#### Data manupulation(split,read) and Analysis,Data mining(Take Insight Information From the Datas) libraray built in py
#### Pandas Offers:
                  ->Data Structure(array,dataframe,matrics)
                  ->Manupulating numerical tables()
                  ->Various Formats
                  ->Merging & Join Dataset(join->add more colums & merge->add more number of datas)
                  ->Time Series & more
#### Develped By Wes Mckinney in 2008                  


## Import Library

In [1]:
import numpy as np

In [2]:
np.version.version

'2.0.2'

# 1D Array

In [3]:
firstarray = np.array([1,2,3,4,5,6,7])

In [4]:
print(firstarray)

[1 2 3 4 5 6 7]


In [5]:
type(firstarray)

numpy.ndarray

# 2D Array

In [6]:
secondary = np.array([(1,2,3),(4,5,5)])

In [7]:
print(secondary)

[[1 2 3]
 [4 5 5]]


# 3D Array

In [8]:
third_array = np.array([[(1,2,3),(4,5,6),(7,8,9),(10,11,12),(13,14,15),(16,17,18),(16,17,18)]])

In [9]:
third_array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [16, 17, 18]]])

#### c is column and f order in memory,dtype=desired datatype of array , shape:shape of array

In [10]:
fourth_array = np.zeros((1,1))

In [11]:
print(fourth_array)

[[0.]]


## Creating ones array


In [12]:
ones_array = np.ones((3,4))
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

###  Linspace

In [13]:
spaced_num = np.linspace(0,20,10)

In [14]:
spaced_num

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

## Array Manupulation

In [15]:
my_array = np.array([0,1,2,3])

In [16]:
print(my_array)

[0 1 2 3]


In [17]:
arr_ones = np.ones((2,2))

In [18]:
print(arr_ones)

[[1. 1.]
 [1. 1.]]


In [19]:
my_matrix = np.array([(11,18,19),(20,26,91),(11,18,19),(11,18,19)])

In [20]:
print(my_matrix)

[[11 18 19]
 [20 26 91]
 [11 18 19]
 [11 18 19]]


### Transpose

In [21]:
transpose_array = np.transpose(my_matrix)
print(transpose_array)

[[11 20 11 11]
 [18 26 18 18]
 [19 91 19 19]]


In [22]:
my_matrix.ravel()

array([11, 18, 19, 20, 26, 91, 11, 18, 19, 11, 18, 19])